#!/usr/bin/env bash
set -euo pipefail

export VISION_RPI_MODE=1
export VISION_CAMERA_INDEX="${VISION_CAMERA_INDEX:-0}"
export VISION_USE_TFLITE="${VISION_USE_TFLITE:-1}"
export VISION_SHOW_WINDOW="${VISION_SHOW_WINDOW:-0}"
export QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-offscreen}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-2}"
export TF_NUM_INTRAOP_THREADS="${TF_NUM_INTRAOP_THREADS:-2}"
export TF_NUM_INTEROP_THREADS="${TF_NUM_INTEROP_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-2}"
export VISION_OPENCV_THREADS="${VISION_OPENCV_THREADS:-2}"
export VISION_SUPPRESS_ALSA_ERRORS="${VISION_SUPPRESS_ALSA_ERRORS:-1}"
export VISION_STT_MIC_PREFERRED_WORDS="${VISION_STT_MIC_PREFERRED_WORDS:-pipewire,pulse,default,headset,hands-free,airpods,freebuds,microphone,mic,input,capture}"
export VISION_STT_MIC_SKIP_WORDS="${VISION_STT_MIC_SKIP_WORDS:-usb audio device}"
export VISION_WAKE_GOOGLE_INTERVAL="${VISION_WAKE_GOOGLE_INTERVAL:-8}"

if [ -d ".venv" ]; then
  source .venv/bin/activate
fi

python main.py
